# Generated by Django 2.2.9 on 2020-09-19 04:01

from django.db import migrations, models
import ingenialo.products.models.image


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=ingenialo.products.models.image.upload_image_path)),
                ('active', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.ManyToManyField(to='products.Image'),
        ),
    ]
