# Generated by Django 2.2.7 on 2019-11-11 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageHero', models.ImageField(upload_to=None)),
                ('tittle', models.CharField(blank=True, max_length=50, null=True)),
                ('legend', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
