# Generated by Django 2.2.7 on 2019-11-11 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20191111_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='hero',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
